# Generated by Django 4.0.5 on 2022-06-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calc_operation_alter_calc_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='operand1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='calc',
            name='operand2',
            field=models.CharField(max_length=200),
        ),
    ]
